### ISSUE TITLE
Windows job print fine but GCP state is error.

### ISSUE THREAD

**Issue by jay0lee** [google/cloud-print-connector#157]
When compiling Jacob's new Windows code and sending print jobs, job state is always recorded as ERROR even though job seems to be printing properly. Console logs show:

2015-Dec-21 16:27:50 INFO Finished synchronizing 1 printers
2015-Dec-21 16:27:50 INFO Ready to rock as proxy 'gcp-win-testing'
Ready to rock as proxy 'gcp-win-testing'
2015-Dec-21 16:28:27 INFO [Job 0d7d80bb-9d4f-2544-6eda-baaf5d5b7c03] Received from cloud
2015-Dec-21 16:28:28 INFO [Job 0d7d80bb-9d4f-2544-6eda-baaf5d5b7c03] Downloaded in 787.1125ms
2015-Dec-21 16:28:29 INFO [Job 0d7d80bb-9d4f-2544-6eda-baaf5d5b7c03] Submitted as native job 212
2015-Dec-21 16:28:30 INFO [Job 0d7d80bb-9d4f-2544-6eda-baaf5d5b7c03] State: ABORTED

[gcp-windows-job.json.txt](https://github.com/google/cups-connector/files/69006/gcp-windows-job.json.txt)

**Comment by jacobmarble** [comment]
I'll have to add some debug logs for you.

I have experienced a problem where Windows decides that a job doesn't exist before the status is "done". In this case, I mark the job as aborted. I'll look at that closer, too.

**Comment by mfly** [comment]
Issue still exists, at least on Win7 and Win8.1.

The problem is that `JOB_CONTROL_RELEASE` is set by `jobContext.free()` which is called at the end of `Print()` in `winspool.go`. This cancels `JOB_CONTROL_RETAIN` behavior and causes job to be immediately removed by the system after printing. Therefore, when the job is finished, call to `GetJob()` returns error which is translated to ABORTED state.

Quick fix is to remove `JOB_CONTROL_RELEASE` call from `jobContext.free()`. It makes jobs stay in queue with `Status == 0x3000 == JOB_STATUS_RETAINED | JOB_STATUS_COMPLETE`.

Jobs retaining in the queue forever may be however considered a downside of this solution. This behavior can be avoided by releasing jobs on completion/failure.

**Comment by jacobmarble** [comment]
Perhaps `JOB_CONTROL_RELEASE` can be called 1 or 2 minutes later with some async mechanism. Thanks for this analysis.

**Comment by jay0lee** [comment]
@arastooz this issue should probably block first Windows release.
