### ISSUE TITLE
Connector should retry and not exit on cloud connection problems

### ISSUE THREAD

**Issue by ajorg** [google/cloud-print-connector#160]
Local operation makes the connector useful even if there is some problem connecting to the cloud. When not connected to the cloud printers advertised by the connector remain offline, so there is an indicator to operators and end users that there is a problem with the connector. Internet connections are sometimes not completely stable during early startup (after a power failure for example) and operator interaction should not be required to get the connector running again.

The connector already retries when connection problems are encountered after startup. There seems to be no reason to differentiate between startup and later connection problems.

See additional discussion on https://github.com/google/cups-connector/issues/140

**Comment by jacobmarble** [comment]
Now for the sad part. This requires some untangling, so will take some time. I don't have a lot of time currently, so don't expect me to do anything soon. (I always have time for pull requests).

To anyone else that needs this feature:
- Please comment so that I can re-prioritize as needed.
- Workarounds to this (and #140)
 - Use local-only mode to eliminate need for a "stable" Internet connection.
 - Add something like `sleep 15` prior to starting the connector on boot.
