### ISSUE TITLE
Stop using undocumented /createrobot

### ISSUE THREAD

**Issue by agoode** [google/cloud-print-connector#243]
Maybe related to #206.

/createrobot is undocumented. The only public documentation is at:
https://developers.google.com/cloud-print/docs/proxyinterfaces
https://developers.google.com/cloud-print/docs/devguide
https://developers.google.com/identity/protocols/OAuth2

Can we stop using this API?
If so, let's.

**Comment by sicklittlemonkey** [comment]
Interesting. If you discover more info but don't commit anything, could you possibly post status updates here?

As you say, documentation is scarce, pretty much just the Dev Guide - which isn't much help since it only relates to creating a robot account when registering a printer.

I take it we still need/want the robot account, primarily for the xmpp_jid.

(I need to inter-op our software with multiple instances of the connector, so I was about to add createrobot to our workflow in order to have values to populate the connector's JSON config file with.)

Cheers,
Nick.

**Comment by agoode** [comment]
The main issue I see with the documented method is that it requires creating a single printer before getting a robot ID. But it looks like you've got it from that point on. I guess that means you could create and then delete a null printer to initialize a robot account?

I have not tried it but it seems plausible.

**Comment by sicklittlemonkey** [comment]
Hmm. Plausible, but ... Perhaps createrobot isn't looking so bad after all. ; - )

And I realized the easiest interop was to leave everything to the util init. Hence #248.

**Comment by jacobmarble** [comment]
When I added this call, it was with great hesitation. The GCP team recommended it. It's used in the Chrome connector. Probably in the old Windows connector service.

**Comment by jcampbell05** [comment]
Do we have some documentation in the code on how this works ?
