### ISSUE TITLE
Printer whitelist

### ISSUE THREAD

**Issue by sicklittlemonkey** [google/cloud-print-connector#261]
I'd like to manage the printers through a whitelist rather than a blacklist. Presumably others might want to do this - the primary advantage being that newly added printers aren't automatically shared before the config file can be updated.

If you give me the go-ahead I'll raise a pull request.

On a related note, on Windows it would probably also be useful to have a ports blacklist and populate that by default to exclude the printer types in the current default blacklist. Ideally the entries would be regexes, primarily to exclude Terminal Server ports created by remote administration with printer redirection enabled (^TS\d+).

**Comment by agoode** [comment]
Both seem like reasonable concepts.

Some questions:
* do you allow both a whitelist and blacklist simultaneously?
  * if so, what is the order of application?
  * do you still want to allow wildcards?
  * how do wildcards work and how will they interact?
* on Windows, are we using the best way to identify a printer? (I haven't looked at that part of the code, so I don't know if there is some GUID or something we should use instead of a name)
* is there an API we can use to definitively find Terminal Server ports regardless of name?

There are probably more questions, but these are good to answer first.

**Comment by sicklittlemonkey** [comment]
Ok, I've added an issue for the port blacklist and answered your question there. It's not on my radar right now. #264

And I've submitted a pull request for the printer whitelist. #263

> Do you allow both a whitelist and blacklist simultaneously?

Yes. At least, I haven't coded to prevent it. In that case the blacklist acts like a kind of safeguard. 

I gave some consideration as to how to enable & disable the whitelist, e.g. a magic entry or separate option. In the end I decided it would be simplest if the default was no whitelist (=empty) and that should behave as before. If you need a whitelist that potentially allows no printers (and I do) then you can add a dummy entry, e.g. an empty string.

> If so, what is the order of application?

It doesn't matter in this case as both are operating on the same list subtractively.

> Do you still want to allow wildcards?

I was only thinking of that for the port blacklist. I suppose it might be useful for the printer lists - sites often have naming schemes with patterns. Wildcards would probably have to be optional though.

> On Windows, are we using the best way to identify a printer? (I haven't looked at that part of the code, so I don't know if there is some GUID or something we should use instead of a name)

The name is what the APIs use, so that's all there is. There's no other unique identifier. 

Cheers,
Nick.
