### ISSUE TITLE
Offline printers should be reported as stopped

### ISSUE THREAD

**Issue by mfly** [google/cloud-print-connector#284]
According to https://developers.google.com/cloud-print/docs/cdd#cds, printer that requires user's attention to continue printing should be marked as "STOPPED".
Currently printers which are offline (e.g. USB cable is not connected) are reported as "IDLE". This can be fixed in CUPS connector by looking for "offline-report" in printerStateReasons. On Windows, this state is visible in PRINTER_INFO_2 attributes - PRINTER_ATTRIBUTE_WORK_OFFLINE flag is set.

Another issue is that Windows marks jobs submitted to offline printers as paused and since https://github.com/google/cloud-print-connector/commit/0d8d28a0b8afa3c53ae384c463f39fa6b554afcd gcp-windows-connector treats paused jobs as done on Windows. This leads to jobs being incorrectly reported as done while still waiting for the printer to be back online.

**Comment by agoode** [comment]
@sicklittlemonkey Can you comment on why paused jobs were changed to report as done on Windows?

**Comment by sicklittlemonkey** [comment]
Sure.

I'm interfacing the GCP connector to our print management solution. Upon arrival (while spooling) jobs are paused for processing (accounting etc) before being released either automatically or at a later time by the user. Stopped ("Was in progress, but stopped due to error or user intervention") sounds like an error and doesn't really describe the state of our jobs - which have successfully made it out of GCP. Hence my desire to avoid it with that change.

A previous version of my pull request (#215) included an option to enable/disable this behaviour, and in there you can see Jacob and I discussing it. For simplicity he suggested I keep the new behaviour and remove the option.

I think this statement above is false: "Windows marks jobs submitted to offline printers as paused". That'll be the driver - they can fudge the printer and job status as they like, so things are not always consistent. I just did a few tests now with various printers and saw something different. Job status always zero. Printer status Offline and Not Available when USB unplugged. Submitted jobs are not paused. When plugged back in Offline disappeared; Not Available remained until a successful print occurred. Also, it pays to test on different types of drivers if possible. (E.g. TCP vs USB.)

Anyway, I can see that my change would cause incorrect behaviour in mfly's case if the driver is pausing the jobs, though normally it's only a user or admin or print management software doing that. Perhaps Stopped is a better status for paused jobs than Printed, so you can revert that part of my change if you like.

**Comment by mfly** [comment]
Thanks for your reply. I confirm that jobs sent to offline printers have status = 0 which is interpreted by the gcp connector the same way as if they were paused [here](https://github.com/google/cloud-print-connector/blob/master/winspool/winspool.go#L545.), excuse me for not being specific enough.

I agree that in this case, marking jobs as STOPPED can be nearly as confusing as marking unfinished jobs as DONE. Maybe the proper way to handle both cases is to mark explicitly paused jobs as PROCESSING and jobs with status 0 as STOPPED?
Paused jobs are definitely not DONE but if this state is caused intentionally by some management software they don't require user intervention.
On the other hand, printjobs sent to offline printer (status == 0) can't be printed until the connection problem is fixed, so STOPPED _"Device cannot process jobs. User should fix the problem to resume..."_ state seems proper in this case.

As for the printer status, I'll do some more tests with other printers (TCP and USB) to verify the  behaviour of `Status` and `Attributes` in `PRINTER_INFO`. @sicklittlemonkey do you have any information on how PRINTER_ATTRIBUTE_WORK_OFFLINE behaves on your printers?

**Comment by mfly** [comment]
Here you can find some test results along with test program source: https://gist.github.com/mfly/0f9c38886a8f5a047f8e02aa74e0c6bd. My test group was very small, but within this group printers seem to behave consistently.

- USB printers control PRINTER_ATTRIBUTE_WORK_OFFLINE and have Status == 0 all the time.  Jobs submitted to disconnected USB printers result in job.Status == 0.
- Network printer state seems to be updated only during despooling. PRINTER_ATTRIBUTE_WORK_OFFLINE is not affected, but PRINTER_STATUS_OFFLINE is set. Submitting a job to offline printer results in job.Status == JOB_STATUS_ERROR | JOB_STATUS_PRINTING | JOB_STATUS_RETAINED.

In both cases, reconnecting the printer results in queued jobs being printed.

**Comment by sicklittlemonkey** [comment]
Hmm, your PRINTER_ATTRIBUTE_WORK_OFFLINE discovery is interesting. I did some more testing too.

For a Lexmark CS725 Windows sets PRINTER_ATTRIBUTE_WORK_OFFLINE (but no printer status changes) on USB disconnect.

For the EPSON TM-T82II USB-only receipt printer that I used for testing yesterday, Windows sets PRINTER_ATTRIBUTE_WORK_OFFLINE and PRINTER_STATUS_NOT_AVAILABLE on USB disconnect.

Setting PRINTER_ATTRIBUTE_WORK_OFFLINE is definitely internal to Windows, with a breakpoint on SPOOLSS!SetPrinterW only hit from the USB port monitor:

SPOOLSS!SetPrinterW
usbmon!DynaMonitor::SetOnlineStatus+0xff
usbmon!DynaMonitor::PortNameNeededBySpooler+0x8f
usbmon!DynaMonitor::ProcessUpdates+0x17a
KERNEL32!BaseThreadInitThunk+0x22
ntdll!RtlUserThreadStart+0x34

For a completeness, here's how Windows 10 reports the status of those printers when disconnected. I usually use Print Management, so you can see why didn't notice PRINTER_ATTRIBUTE_WORK_OFFLINE in my previous testing.

In Print Management:
EPSON TM-T82II - Not Available - Offline
Lexmark CS725 - Offline

In Devices and Printers details view with status:
EPSON TM-T82II - Not Available
Lexmark CS725 - Offline

In Print Queue windows e.g. "See what's printing" from Devices and Printers:
EPSON TM-T82II - Not Available - Use Printer Offline
Lexmark CS725 - Use Printer Offline

So Windows does set and interpret PRINTER_ATTRIBUTE_WORK_OFFLINE as a proxy for PRINTER_STATUS_OFFLINE in some ways for these USB-connected printers. It reminds me of the complexity of printer status errors vs job status errors - which were used (as I discovered back in the 90's) because (like sockets) Windows couldn't detect network disconnect - you had to send a job to discover the error.

So the question is valid as to whether the GCP connector should check PRINTER_ATTRIBUTE_WORK_OFFLINE as your pull request does.
