### ISSUE TITLE
Windows installer dependencies.wxs checked in?

### ISSUE THREAD

**Issue by sicklittlemonkey** [google/cloud-print-connector#297]
I've been looking at the Windows installer.

Some distant Utopian build system will just run generate-dependencies.sh to create dependencies.wxs, so I guess it doesn't necessarily need to be checked in - but it would be handy for keeping track of changing dependencies. Is the plan is to keep it? If so I suggest sorting the entries to make the diffs usable.

Also, I needed to add -i to the grep. I'll add a PR if the following is ok:

````
for f in `ldd ${GOPATH}/bin/gcp-windows-connector.exe | grep -i -v Windows | sed s/" =>.*"// | sed s/"\t"// | sort`
````

Finally, if ldd is working for you in MSYS2, don't upgrade. It was [recently broken but the fix isn't out yet](https://sourceforge.net/p/msys2/tickets/269/).

I'm using cygcheck instead for now, and had to modify the sed regex:
````
for f in `cygcheck ${GOPATH}/bin/gcp-windows-connector.exe | grep -i -v windows | sed s/"[^\]*[\]"//g | sort`
````

**Comment by arastooz** [comment]
The change sounds good to me.

I think leaving dependencies.wxs checked in makes sense.

Generally with build systems, I have always tried to avoid having the build system do dependency checking at build time or any sort of dynamic installer builds (e.g. InstallShield's "Extract at Build"), because of problems it creates.  First, the dependencies determined are dependent upon the build machine setup.  If you build on a 32-bit Win7 machine, it's possible the dependencies turn out to be different than if you're building on a 64-bit Win10 machine.  It also often places the requirement that your build machine can actually execute the binaries it's building, which is not always something you want, and in the Windows world, that can mean that your build has to run elevated, which implies often that your unit tests run elevated, which can result in unintended test behavior.

While a lot of those wouldn't necessarily be problems with this project, it's still something I try to avoid.  But I definitely like tools that can be run at a developer's desk and make their jobs easier.  I also like having the file in source control so you can see differences, and make sure that any added dependencies are really intentional.  It's harder to detect those issues if it's all automated.

**Comment by sicklittlemonkey** [comment]
Yes, all good points - thanks for your insight. My dev environment is not conducive to quick check-ins, but I'll get around to it eventually unless someone else does first. ; - )
