### ISSUE TITLE
Windows installer silent install

### ISSUE THREAD

**Issue by sicklittlemonkey** [google/cloud-print-connector#299]
I have a need for this but don't know WiX yet (it has a notoriously steep learning curve).

It's easy enough to remove the ServiceControl "Start" attribute for my build, but it would be nice if there was a switch that could be used out of the box.

Also, out of interest, is there a reason the installer runs the util in TempFolder to generate the config file and then copies it to the data folder rather than using --config-filename?

**Comment by arastooz** [comment]
Silent installs can be done by running:
`msiexec /qn /i <path_to_msi>`
See https://msdn.microsoft.com/en-us/library/windows/desktop/aa367988(v=vs.85).aspx

Is there a reason to skip starting the service?  It's possible to add a property that can be set to turn that off.  But the intended use for a silent install would be:
1) Run util to create the config file before running the install
2) Set the property CONFIGFILE to the path to the config file that was created during the install.  For example:
`msiexec /qn /i C:\MyFolder\windows-connector.msi CONFIGFILE=C:\MyFolder\gcp-windows-connector.config.json`
Running silently (or using CONFIGFILE) skips the part that runs the util during the install, and the install just copies the config file to Program Data, and then the service should start successfully.

Regarding the temp folder:
The installer runs the util in the temp folder because the util has to run during the install UI phase in order to display the console UI, which runs as the user who runs the install (unelevated).  So, it has to create the file in a folder where the current user has permission to create files (ie. not Program Files).  So, it creates the file in temp, then the elevated part of the installer copies the file to its final location.  Initially, the file was in Program Files, not Program Data, so that's why it was done this way.  I changed the install to put the config file in Program Data where all users should have write permissions, but didn't bother changing the write and move process, especially because to support specifying a different config file, the copy process has to be there, and it's easier to have the process be similar whether running util during the install or accepting a separate path to the config file.

**Comment by sicklittlemonkey** [comment]
Thanks. I want to silently install the connector and run the util at a later time, so there is no config.

Currently if there is no config file the service will fail to start a few times and the install will roll-back.

My use case is installing the connector and managing it via software. Admittedly I may be the only one doing this, so although the project owners have been accommodating so far, I neither ask for nor expect anything specific to only my use case.

**Comment by jacobmarble** [comment]
@arastooz other users have asked to be able to install without starting, so that the whitelist/blacklist config value can be updated before printers are created. Let's get clear about other use cases before implementing this change.

**Comment by jay0lee** [comment]
This was fixed by PR #314 

Some of the possible silent install methods:

Run installer but don’t start service:
msiexec /i <file.msi> STARTSERVICE=NO

Run installer but don’t init config file (install likely to fail on service start):
msiexec /i <file.msi> RUNINIT=NO

Append arguments to init:
msiexec /i <file.msi> INITPARAMS=”--gcp-user-refresh-token=<token> --share-scope=”

Tell installer to use existing file as config instead of running init:
msiexec /i <file.msi> CONFIGFILE=”c:\path\to\cloud-print-connector.config.json” STARTSERVICE=NO
net start “Cloud Print Connector”
