### ISSUE TITLE
gcp-connector-util build fails

### ISSUE THREAD

**Issue by zmlcrm** [google/cloud-print-connector#395]
<$ go get github.com/google/cloud-print-connector/...>

results in...

<# github.com/google/cloud-print-connector/gcp-connector-util go/src/github.com/google/cloud-print-connector/gcp-connector-util/init.go:417:26: multiple-value uuid.NewV4() in single-value context>

Am I missing something?

**Comment by DanielCeregatti** [comment]
Same here. I tried go 1.5 and 1.9, both report the above. This is on a fully updated Raspbian Jesse (arm6l according to uname)

**Comment by DanielCeregatti** [comment]
Turns out only gcp-cups-connector was all that was needed to get everything working. The other binary apparently is only used for local configuration. Running gcp-cups-connector caused my local browser to display a page that allowed for the addition of the printer to google drive. Thing is, I ssh from my laptop to the pi, yet somehow that managed to get a page up on my local browser, presumably through X forwarding or some such.

**Comment by ALRubinger** [comment]
Ping with request for PR merge. :)  Issue persisting for me locally as reported by Travis:

https://travis-ci.org/google/cloud-print-connector/jobs/328007814

**Comment by RichardSantos1516059944** [comment]
Confirmed I receive the same issue:
```
root@host:~# go get github.com/google/cloud-print-connector/...
# github.com/google/cloud-print-connector/gcp-connector-util
go/src/github.com/google/cloud-print-connector/gcp-connector-util/init.go:417:26: multiple-value uuid.NewV4() in single-value context
root@host:~# 
root@host:~# go version
go version go1.9.2 linux/amd64
```

**Comment by ScottESanDiego** [comment]
The fix proposed works okay for me.  Pinging again here to request the merge so I don't have to patch manually. :-)

**Comment by normanr** [comment]
This was caused by https://github.com/satori/go.uuid/issues/66. Unfortunately while #397 makes gcp-connector-util build with satori/go.uuid at head, it makes it fail #425 with the most recent release (v1.2.0)!
