### ISSUE TITLE
Issue sharing to devices

### ISSUE THREAD

**Issue by Gaz2600** [google/cloud-print-connector#410]
Google Support suggested I move to Connector from the old GCP Service app.  To reduce user downtime I installed Connector while the service app was running, everything seemed ok, users could still print, the new Connector was syncing printers to the cloud.  I migrated all my device shared printers off the service app and to the Connector app.  After waiting the recommended 24 hours I found the printers were not showing up on the devices.  I called support and tried isolating some devices, put them in their own OU with no restriction or forced apps, removed firewall settings on the server side so it had full access, still had the same issue.  I downgraded from version 1.16 (https) to 1.13 (http) still had the same issue.  Finally gave up and uninstalled connector and reinstalled GCP Service, which was working prior to the connector install, it is now having the same issue as connector.  Support does not seems to have any more ideas on how to fix this issue and my users are not able to print.

**Comment by jay0lee** [comment]
Sharing the printers to devices is not directly related to the connector/service you are using. A few things to check:

1) make sure the user you are logging into the connector with is at least a delegated admin with Chrome rights in your admin console so that the user can share the printer with your devices via admin.google.com.

2) As support said, sharing to the devices can sometimes take 24 hours to show on all devices, sharing directly with users or groups should be quicker so if that's an option I'd recommend it.

3) If you still have issues please re-open or start a new support case and post the case number here, I'll see if I can get the right eyes on the issue.

Closing this for now as it's not a connector-specific issue but again, if you re-open the case, you should still be able to post the case # here.

**Comment by Gaz2600** [comment]
The user I am using for sharing printers is a super admin on the Google
side and domain admin on the Active Directory side.

Normally printers show up vary quickly within a minute of adding them,
regardless I waited all weekend and they still are not showing up.

Support does not want to open another case number and are not familiar with
you or the github site, my existing numbers are 15522973 and 15486890.

My contact info on the case is guizzettim@eastmont206.org

Thank you

**Comment by jay0lee** [comment]
Thanks, I've followed up on the case.
